version: "3"

services:
  proxy:
    image: hanschrome/solidjobs-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - app_network
    restart: always

  backend:
    image: php:7.4-fpm
    container_name: php-fpm
    networks:
      - app_network
    restart: always

  backend_nginx:
    image: nginx:latest
    container_name: nginx-backend
    ports:
      - "8002:8002"
    networks:
      - app_network
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
    environment:
      - PHP_FPM_HOST=backend
    restart: always

  frontend:
    image: hanschrome/solidjobs-web
    container_name: nginx-frontend
    ports:
      - "8001:8001"
    networks:
      - app_network
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    restart: always

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - app_network
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always

networks:
  app_network:
    driver: bridge

