version: "3"

services:
  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    restart: always

  backend:
    image: php:7.4-fpm
    container_name: php-fpm
    networks:
      - app_network
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    restart: always

  backend_nginx:
    image: nginx:latest
    container_name: nginx-backend
    ports:
      - "8080:80"
    networks:
      - app_network
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - backend
    restart: always

  frontend:
    image: nginx:latest
    container_name: nginx-frontend
    ports:
      - "8081:80"
    networks:
      - app_network
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - proxy
    restart: always

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - app_network
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always

networks:
  app_network:
    driver: bridge

